[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "TODO: Fill in your Thunderstore team name here"
name = "YapLocalizer"
description = "TODO: Fill in short mod description."
websiteUrl = "" # TODO: Add a link to your mod repository here (optional)
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/YapLocalizer/release/com.github.darmuh.yaplocalizer.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
# replace _ThunderstoreGameIdentifier_ with community name in this file
communities = [ "_ThunderstoreGameIdentifier_", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/_ThunderstoreGameIdentifier_/category/
_ThunderstoreGameIdentifier_ = [ "mods", ]
