[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "darmuh"
name = "YapLocalizer"
description = "Utility mod for adding localized text to the game!"
websiteUrl = "https://github.com/darmuh/YapLocalizer"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2304"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/YapLocalizer/release/com.github.darmuh.yaplocalizer.dll"
target = "plugins/"

[[build.copy]]
source = "../../artifacts/bin/YapLocalizer/release/com.github.darmuh.yaplocalizer.xml"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "yapyap", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/yapyap/category/
yapyap = [ "mods", "tools", ]
